### PR TITLE
Add Collections Support (including Purchases)

### PR DESCRIPTION
**Pull request by triple-j**
This PR adds support for what can be found on the user's Library/Collections page (https://itch.io/my-collections). That page contains all the user's created private and public collections as well as their "Things you own" collection (https://itch.io/my-purchases) that includes all of their purchased games.

This also works with other user's public collections: https://itch.io/c/2396329/games-im-excited-to-play

### CODE REVIEW

**Comment by DragoonAethis** [comment]
Hey, apologies for taking this long with merging. I'm a bit swamped with stuff outside of work and couldn't find the time to get here... I'll cut a new release later this week with your changes. Thanks for the contribution!

**Comment by avivace** [comment]
Thanks @DragoonAethis and @triple-j !

**Comment by TheFrenchGhosty** [comment]
@DragoonAethis You should really document this feature more, this is one of the most useful feature of this tool since it's literally the only tool able to do it - the other itch downloader ( https://github.com/Emersont1/itchio ) being broken

**Comment by DragoonAethis** [comment]
@TheFrenchGhosty I've added a list of supported download sources with examples to the README.

**Pull request merged**
